import vuetify from 'eslint-config-vuetify'

export default vuetify({
  rules: {
    // Desabilitar regras de ordenação
    'sort-imports': 'off',
    'import/order': 'off',
    'sort-keys': 'off',
    'vue/sort-keys': 'off',
    'vue/attributes-order': 'off',
    'perfectionist/sort-imports': 'off',
    'perfectionist/sort-named-imports': 'off',
    'perfectionist/sort-exports': 'off',
    '@typescript-eslint/no-unused-vars': 'off',
    'prefer-destructuring': 'off',
    'unicorn/no-array-method-this-argument': 'off',
    'unicorn/prefer-array-some': 'off',
    'unicorn/prefer-modern-math-apis': 'off',
    'unicorn/prefer-at': 'off',
    'unicorn/prefer-string-replace-all': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/prefer-spread': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/prefer-top-level-await': 'off',
    'unicorn/numeric-separators-style': 'off',
    'unicorn/catch-error-name': 'off',
    'unicorn/prefer-array-flat-map': 'off',
    'unicorn/prefer-number-properties': 'off',
    'unicorn/prefer-set-has': 'off',
    'unicorn/prefer-node-protocol': 'off',
    'unicorn/prefer-array-prototype-at': 'off',
    'unicorn/prefer-string-slice': 'off',
    'unicorn/no-useless-undefined': 'off',
    'unicorn/prefer-ternary': 'off',
    '@stylistic/space-before-function-paren': 'off',
    '@stylistic/arrow-parens': 'off',
    '@stylistic/comma-dangle': 'off',
    'prefer-const': 'off',
    'vue/html-self-closing': 'off',
  },
})
