/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BarChartCard: typeof import('./components/BarChartCard.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    GameTabs: typeof import('./components/GameTabs.vue')['default']
    PieChartCard: typeof import('./components/PieChartCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCards: typeof import('./components/StatsCards.vue')['default']
  }
}
